apiVersion: v1
kind: ConfigMap
metadata:
  name: api-pagamento-configmap
data:
  SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb-server-fiapfood.mariadb.database.azure.com:3306/fiapfood
  SPRING_PROFILES_ACTIVE: prod
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MariaDBDialect
  SPRING_DATA_MONGODB_URI: mongodb+srv://wtof:cosmoDB10@fiapcosmodbcluster.mongocluster.cosmos.azure.com/test?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
  FEIGN_CLIENT_PEDIDO_URL: http://fiapfood-pedido-service:8081
