version: '3.8'

services:
  app:
    image: wtof/fiapfood-pagamento:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/test
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/fiapfood_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - mongodb
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - my_network

networks:
  my_network:
    external:
      name: fiapfood-pedido_my_network