version: '3.8'

services:
  app:
    image: wtof/fiapfood-pagamento:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/test
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/fiapfood_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db
      - mongodb

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=fiapfood_db
    ports:
      - 3307:3306

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017